<a href="https://colab.research.google.com/github/dlwogns/ML-DL/blob/main/basic%20implementation/RNN_ihello.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import matplotlib.dates as mdates
import tensorflow as tf

RNN INPUT dimension을 살펴보자.<br>
[
[ [0,0,0,1], [0,0,1,0], [0,1,0,0] ]

[ [0,0,0,1], [0,0,1,0], [0,1,0,0] ]

[ [0,0,0,1], [0,0,1,0], [0,1,0,0] ]
]
<br>의 데이터가 들어오면
(3, 3, 4)이다.<br>
첫번째 인자는 batch_size로 이 데이터에선 3개이다.<br>
두번째는 sequence_length로, 여기선 3이된다.<br>
세번째는 one-hot size, hiddensize로 0,0,1,0과 같이 4개이므로 4이다.

In [3]:
idx2char = ['h','i','e','l','o']
# hihell -> ihello
# char을 one hot encoding으로, 즉 index로 변형시킨다.
# x_data = [[0,1,0,2,3,3]]
y_data = [[1,0,2,3,3,4]]

In [4]:
num_classes = 5 #output size
input_dim = 5 
# h -> [1,0,0,0,0]과 같이 5개로 표현하기 때문에 class는 5이다.
# one-hot size, same as hidden size
sequence_length = 6 # ihello의 크기, 6
learning_rate = 0.1

In [5]:
x_one_hot = np.array([[[1, 0, 0, 0, 0],    # h 0
                       [0, 1, 0, 0, 0],    # i 1
                       [1, 0, 0, 0, 0],    # h 0
                       [0, 0, 1, 0, 0],    # e 2
                       [0, 0, 0, 1, 0],    # l 3
                       [0, 0, 0, 1, 0]]],  # l 3
                     dtype=np.float32)
y_one_hot = tf.keras.utils.to_categorical(y_data, num_classes = num_classes)

In [7]:
tf.model = tf.keras.Sequential()

In [9]:
cell = tf.keras.layers.LSTMCell(units=num_classes, input_shape=(sequence_length, input_dim))
# input_shape = (1,6,5) 상단의 설명 참조.
# units = output_shape, 5
tf.model.add(tf.keras.layers.RNN(cell=cell, return_sequences=True))
tf.model.add(tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(units=num_classes, activation='sigmoid')))
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(lr=learning_rate), metrics=['accuracy'])

/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_v2/adam.py:110: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [10]:
tf.model.fit(x_one_hot, y_one_hot, epochs=50)

Epoch 1/50
1/1 [==============================] - 2s 2s/step - loss: 1.6090 - accuracy: 0.3333
Epoch 2/50
1/1 [==============================] - 0s 10ms/step - loss: 1.5528 - accuracy: 0.3333
Epoch 3/50
1/1 [==============================] - 0s 8ms/step - loss: 1.4964 - accuracy: 0.3333
Epoch 4/50
1/1 [==============================] - 0s 8ms/step - loss: 1.4392 - accuracy: 0.3333
Epoch 5/50
1/1 [==============================] - 0s 10ms/step - loss: 1.3731 - accuracy: 0.3333
Epoch 6/50
1/1 [==============================] - 0s 14ms/step - loss: 1.2942 - accuracy: 0.3333
Epoch 7/50
1/1 [==============================] - 0s 9ms/step - loss: 1.2123 - accuracy: 0.3333
Epoch 8/50
1/1 [==============================] - 0s 10ms/step - loss: 1.1360 - accuracy: 0.3333
Epoch 9/50
1/1 [==============================] - 0s 9ms/step - loss: 1.0631 - accuracy: 0.3333
Epoch 10/50
1/1 [==============================] - 0s 11ms/step - loss: 0.9910 - accuracy: 0.3333
Epoch 11/50
1/1 [==================

In [12]:
tf.model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 rnn (RNN)                   (None, 6, 5)              220       
                                                                 
 time_distributed (TimeDistr  (None, 6, 5)             30        
 ibuted)                                                         
                                                                 
Total params: 250
Trainable params: 250
Non-trainable params: 0
_________________________________________________________________


In [13]:
predictions = tf.model.predict(x_one_hot)
for i, prediction in enumerate(predictions):
    print(prediction)
    # print char using argmax, dict
    result_str = [idx2char[c] for c in np.argmax(prediction, axis=1)]
    print("\tPrediction str: ", ''.join(result_str))

1/1 [==============================] - 1s 554ms/step
[[3.2675378e-03 6.6963291e-01 1.7389396e-03 3.8829970e-03 2.0300760e-03]
 [1.7841005e-01 3.9871735e-04 5.8803573e-04 4.0056073e-04 2.0226369e-05]
 [1.8659845e-03 7.8272098e-04 5.2956784e-01 9.6476497e-04 1.2250486e-05]
 [6.6049094e-04 1.9047111e-05 2.7177139e-04 2.9484957e-01 2.7382505e-04]
 [5.8789866e-04 6.1743076e-06 4.0323263e-05 9.0207225e-01 8.1771715e-03]
 [8.4616295e-06 9.9477591e-03 9.5990058e-03 9.9918044e-01 9.7872043e-01]]
	Prediction str:  ihelll
